Switch to using new book management API
diderot-edu/diderot-cli pull request #92
Opened 2020-08-21 16:08 UTC by bojanbg

Does away with using Django views for authentication and book management. With this change only DRF views are used by `diderot-cli`.

I've manually tested all book management commands except `upload_book` (for which I don't have good test data). I've added some automated tests.

Note that this mustn't be merged before https://github.com/umutacar/lambdabricks/pull/4208, otherwise it will break the cli.

2020-09-03 23:22 UTC, rohany requested changes
small requests. I can pick them up, or you could do them on your own time if you'd like. Does the integration test suite in the diderot repo pass with these changes?

2020-09-03 23:22 UTC, rohany commented on api_calls.py
> +    # login logs into Diderot to get the authentication token
bump

2020-09-03 23:22 UTC, rohany commented on api_calls.py
> +        login_url = urllib.parse.urljoin(self.url, "/frontend-api/users/login/")
mind making this string a constant?

2020-12-04 15:40 UTC, GodMode-On commented
@umutacar Can we merge it, or I can continue on this branch?

2020-12-08 16:33 UTC, umutacar commented
@GodMode-On thank you for the updates.
Let's wait to merge this until December 22 (the end of semester) so that we don't cause things to break.  
As I understand it, we would then need to update the submodule in the Diderot repo, to test this thoroughly.

2020-12-08 17:48 UTC, rohany commented
> As I understand it, we would then need to update the submodule in the Diderot repo, to test this thoroughly.

That's correct. It's a good idea to check out this commit in the submodule and run the Diderot tests before merging though, and fixing the bugs that it finds.

2021-01-27 18:28 UTC, rohany commented
@moridyn ping me when this is ready for a review

2021-05-17 14:52 UTC, moridyn commented
@rohany it is ready for review.

2021-05-18 02:10 UTC, rohany requested changes
Looks good, mostly nits.

2021-05-18 02:10 UTC, rohany commented on api_calls.py
> +    # login logs into Diderot to get the authentication token
please fix this

2021-05-18 02:10 UTC, rohany commented on api_calls.py
> +            (MANAGE_BOOK_API + "manage-chapters/{chapter_id}/{action}/").format(**route_params)
can this be a constant

2021-05-18 02:10 UTC, rohany commented on api_calls.py
> +                (MANAGE_BOOK_API + "manage-chapters/{chapter_id}/{action}/").format(**route_params),
same here

2021-05-18 02:10 UTC, rohany commented on test_book_management.py
> +    url = (MANAGE_BOOK_API + "manage-chapters/{chapter_id}/{action}/").format(**route_params)
can use that constant here

2021-05-20 04:32 UTC, rohany reviewed
Looks good! Please squash the commits into a single commit and then merge

2021-05-20 07:14 UTC, rohany approved these changes

2021-05-20 07:16 UTC, merged