Update lab download link/error handling
diderot-edu/diderot-cli pull request #95
Opened 2020-09-01 19:08 UTC by mooey5775

I noticed lab downloads silently erroring out for 15-210 labs. It seems to me like the base_path should contain `codelabs-production` instead of `diderot-codelabs-production`, so I changed over the URL. If this isn't the case, feel free to edit.

Additionally, to avoid silent errors, I updated status code handling on `download_file_helper` and catch it in download_assignment in case no writeup exists.

2020-09-01 19:17 UTC, mooey5775 commented
Seems like `test_download_assignment` is failing. It seems like this is an issue with the test, as the assignment handout URL is giving me permission denied errors when I try to fetch from AWS.

This test passed on previous builds because `diderot-cli` would claim that it successfully downloaded the assignment even when non-200 status codes were received.

2020-09-10 17:32 UTC, rohany requested changes
Thanks for the fix (and sorry for the delay in reviewing). You're right about the URL being broken. However, we would still like to swallow these errors instead of raising them to the user. I would catch this error for both of the files being downloaded here, and print a message like `Sprintf("Could not find a %s for assignment %s", kind (either handout, writeup), lab.name)`

2020-09-14 02:02 UTC, mooey5775 commented
Thanks for the review - sorry for the delay in fixing it.

I've swallowed writeup/handout errors. Now it prints what you suggested when each fails. Additionally, since the errors are swallowed, it claims that it successfully downloads the file even when both writeup and handout were not found (I assumed this was intended behavior if swallowing errors).

Let me know if you'd like me to squash my commits into 1.

2020-09-14 05:00 UTC, rohany commented
This looks good! Yes, please squash + rebase and I will merge.

2020-09-14 05:41 UTC, mooey5775 commented
Ok, squashed and rebased

2020-09-14 05:44 UTC, rohany approved these changes

2020-09-14 05:44 UTC, merged

2020-09-14 05:45 UTC, rohany commented
Thanks for your contribution!